### ISSUE TITLE
Wrong links for pages regarding Helios4

### ISSUE THREAD

**Issue by anothernewusername** [kobol-io/wiki#28]
Starting from 

> https://wiki.kobol.io/helios4/intro

following the link to the install section

> https://wiki.kobol.io/install/

leads to a blank site. The new link should be 

> https://wiki.kobol.io/helios4/install/

which already works but is not yet referenced to. This is the case for pages like mdadm and Nextcloud, too. Maybe it's worth checking all the helios4 sites even if it's EOL.

Thanks in advance and keep up your great work.

**Comment by g-provost** [comment]
Thanks for reporting the issue. We just migrated our wiki to aws cloudfront + S3 and effectively there was an unexpected behavior with relative link when the current page url was missing the trailing '/'. Now it's fix  with 79b964612de642c302e945acf413e5ea163dc8e3
